# Generated by Django 4.2 on 2025-05-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0005_favoriteplace_is_default_favoriteplace_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='search',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='search',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='search',
            name='time',
        ),
        migrations.AddField(
            model_name='search',
            name='from_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='search',
            name='from_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='search',
            name='modes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='to_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='search',
            name='to_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='search',
            name='trip_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteplace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
