# Generated by Django 4.2 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_search_anonymous_session_key_alter_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
