# Generated by Django 4.2 on 2025-06-11 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_favoriteplace_latitude_favoriteplace_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
