# Generated by Django 4.2 on 2025-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_booking_distance_km_emissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='co2_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='EmissionRecord',
        ),
    ]
