# Generated by Django 4.2 on 2025-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_booking_co2_kg_delete_emissionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='co2_saved_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
