# Generated by Django 4.2 on 2025-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('student', 'Student'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
